backbone:
  backbone_name: DINOv2Backbone
  params:
    model_name: dinov2_vits14
    resolution: 448
model:
  model_name: MemoryBankModel
  params:
    dataset_name: mvtec_ad
    data_root: /Users/theo.moreau/Documents/futur/datasets/mvtec_anomaly_detection
    object_names: ["screw"]
    device: mps
    shots: 10
    informed_preprocessing: False
    processing_config_path: /Users/theo.moreau/Documents/futur/src/benchmark/memory_bank/configs/object_preprocessing
    use_patch_features: True
    seed: 157
